# Generated by Django 4.0.3 on 2022-03-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_state',
            field=models.CharField(choices=[('TODO', 'TODO'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='TODO', max_length=12),
        ),
    ]
